version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-prod
    image: hmohammed2/frontend:v1
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-prod
    image: hmohammed2/backend:v1
    ports:
      - "7777:7777"
    environment:
      - MONGODB_URL=${MONGODB_URL}
    depends_on:
      - mongodb
